// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llxarjjiqcopshszisay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxseGFyamppcWNvcHNoc3ppc2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzY5OTUsImV4cCI6MjA2OTY1Mjk5NX0.fnNBO4I05ySb9MDhp6ZZ1nLC_fPXO7iRDYOAj_c-78o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});